name: cineradar
description: "CineRadar es una aplicación que proporciona información detallada sobre películas, incluyendo géneros, sinopsis, trailers y más. Descubre nuevas películas y mantente al día con las últimas novedades del cine."
publish_to: 'none'
version: 0.2.0+3

environment:
  sdk: ^3.5.2

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  change_app_package_name: ^1.4.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.1.4
  flutter_inappwebview_platform_interface: ^1.3.0+1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.2.7
  icons_plus: ^5.0.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.4.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Titulo
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
